name: kph2
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - mlflow
  - spacy
  - torchtext
  - pytorch 
  - torchvision 
  - cudatoolkit=10.1
  - numpy
  - pip
  - pip:
    - "--editable=git+https://github.com/iacopy/pymed.git@fork-fixes#egg=pymed"
    - pytorch-crf

