name: kph2
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - mlflow
  - spacy
  - torchtext
  - pytorch 
  - torchvision 
  - cudatoolkit=10.1
  - numpy
  - pip
  - pip:
    - pymed==0.8.9
    - pytorch-crf

